openapi: 3.0.0
info:
  title: Solana Wallet Checker
  version: 1.0.0
servers:
  - url: https://solgpt-production.up.railway.app
paths:
  /wallet/{address}:
    get:
      summary: Get wallet info
      operationId: getWalletInfo
      parameters:
        - name: address
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Wallet data returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  address:
                    type: string
                  sol_balance:
                    type: number
                  tokens:
                    type: array
                    items:
                      type: object
                      properties:
                        mint:
                          type: string
                        amount:
                          type: string
                        decimals:
                          type: integer
        '404':
          description: Wallet not found
